application:
  port: 8000
  host: 0.0.0.0
  hmac_secret: "verylongverysecretstringverylongverysecretstringverylongverysecretstring"
database:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "locahost"
  sender_email: "test@gmail.com"
  auth_token: "gloria-invigilata"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"